export const SET_COURSE_STATUS = 'SET_STATUS';

export const CourseStatuses = {
  NOT_STARTED: 'NOT_STARTED',
  STARTED: 'STARTED',
  COMPLETED: 'COMPLETED',
};

export const MODULE_DONE = 'MODULE_DONE';

export const ASSESSMENT_DONE = 'ASSESSMENT_DONE';

export const LOGIN = {
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  FAILURE: 'LOGIN_FAILURE',
};

export const LOGOUT = 'LOGOUT';
